"""Daily bars into percentiles, a pillar score and a dated snapshot.

Five of the seven modules are pure -- they take plain values and return plain
values -- as `screener.ingest` separates `parse` from `load`. `peers` and `run`
are the two that open a connection, and nothing here opens a socket.
"""

from screener.scoring.adjust import Action, adjusted_closes
from screener.scoring.basis import (
    ANNUAL,
    ANNUAL_MAX_AGE_DAYS,
    QUARTER_GAP_MAX_DAYS,
    QUARTER_GAP_MIN_DAYS,
    SPLIT_WINDOW_DAYS,
    TTM,
    TTM_MAX_AGE_DAYS,
    Basis,
    Held,
    Item,
    annual_basis,
    balance_at,
    flow_basis,
    index_facts,
    market_cap,
    newest_balance,
    ttm_basis,
)
from screener.scoring.blend import AGREEMENT_THRESHOLD, Snapshot, blend
from screener.scoring.metrics import CODES, compute, months_before
from screener.scoring.percentile import deciles, percentiles
from screener.scoring.peers import MIN_PEERS, Peer, market_group, resolve
from screener.scoring.pillars import PillarScore, score_pillar
from screener.scoring.ranking import GroupStat, Placed, rank
from screener.scoring.ratios import (
    BALANCE_SHEET,
    QUALITY,
    RATIO_CODES,
    REIT,
    STANDARD,
    TAX_RATE_CEILING,
    VALUATION,
    Ratio,
    applicable,
    compute_ratios,
    industry_class,
)
from screener.scoring.run import (
    BAR_WINDOW_MONTHS,
    CUTOFF_OFFSET,
    LOGIC_DESCRIPTION,
    PILLAR_CODE,
    SCORING_LOCK_ID,
    WEIGHT_CODE,
    NoBarsVisible,
    Reference,
    ScoringInProgress,
    ScoringReport,
    active_securities,
    read_actions,
    read_bars,
    reconcile,
    reference,
    run_scoring,
    score,
    visibility_cutoff,
)

__all__ = [
    "AGREEMENT_THRESHOLD",
    "ANNUAL",
    "ANNUAL_MAX_AGE_DAYS",
    "BALANCE_SHEET",
    "BAR_WINDOW_MONTHS",
    "CODES",
    "CUTOFF_OFFSET",
    "LOGIC_DESCRIPTION",
    "MIN_PEERS",
    "PILLAR_CODE",
    "QUALITY",
    "QUARTER_GAP_MAX_DAYS",
    "QUARTER_GAP_MIN_DAYS",
    "RATIO_CODES",
    "REIT",
    "SCORING_LOCK_ID",
    "SPLIT_WINDOW_DAYS",
    "STANDARD",
    "TAX_RATE_CEILING",
    "TTM",
    "TTM_MAX_AGE_DAYS",
    "VALUATION",
    "WEIGHT_CODE",
    "Action",
    "Basis",
    "Held",
    "Item",
    "GroupStat",
    "NoBarsVisible",
    "Peer",
    "PillarScore",
    "Placed",
    "Ratio",
    "Reference",
    "ScoringInProgress",
    "ScoringReport",
    "Snapshot",
    "active_securities",
    "adjusted_closes",
    "annual_basis",
    "applicable",
    "balance_at",
    "blend",
    "compute",
    "compute_ratios",
    "deciles",
    "flow_basis",
    "index_facts",
    "industry_class",
    "market_cap",
    "market_group",
    "months_before",
    "newest_balance",
    "percentiles",
    "rank",
    "read_actions",
    "read_bars",
    "reconcile",
    "reference",
    "resolve",
    "run_scoring",
    "score",
    "score_pillar",
    "ttm_basis",
    "visibility_cutoff",
]
