"""The scored screen, read for the dashboard and for Steven (ui-swap spec D6).

Pure modules and reading modules are kept apart, as `screener.ingest` keeps
`parse` from `load`. `rows`, `params` and `shape` are pure: typed records parsed
from either a psycopg cursor or a `playground.Result`, query strings refused by
name, and JSON built from typed rows. `queries` holds every statement as a
literal. `read` resolves which night is served and reads it, and `explain`
re-runs scoring's explaining forms for one security under the run's own view,
giving each metric one of six statuses.
"""

from screener.screen.params import (
    DEFAULT_LIMIT,
    MAX_LIMIT,
    MAX_OFFSET,
    MAX_SYMBOL,
    PARTIALS,
    SORTS,
    BadParameter,
    ScreenParams,
    SecurityParams,
    screen_params,
    security_params,
)
from screener.screen.read import (
    CHART_CLOSES,
    CLOSE_LOOKBACK_DAYS,
    SPARKLINE_CLOSES,
    RunChanged,
    previous_run,
    read_screen,
    resolve_run,
)
from screener.screen.shape import (
    ALL_CODES,
    MULTIPLE,
    PERCENT,
    PILLAR_KEYS,
    PILLAR_ORDER,
    UNITS,
    awaiting,
    closes,
    delta,
    exact,
    one_decimal,
    partial,
    price,
    run_payload,
    screen_payload,
    screen_row,
    sector,
)
from screener.screen.rows import (
    ActionRow,
    BarRow,
    ClassificationRow,
    MetricInfoRow,
    MetricRow,
    PillarRow,
    PreviousRunRow,
    RunRow,
    ScreenRow,
    SectorRow,
    SnapshotRow,
    SymbolRow,
    TilesRow,
    parse,
    parse_all,
)

__all__ = [
    "ALL_CODES",
    "CHART_CLOSES",
    "CLOSE_LOOKBACK_DAYS",
    "DEFAULT_LIMIT",
    "MAX_LIMIT",
    "MAX_OFFSET",
    "MAX_SYMBOL",
    "MULTIPLE",
    "PARTIALS",
    "PERCENT",
    "PILLAR_KEYS",
    "PILLAR_ORDER",
    "SORTS",
    "SPARKLINE_CLOSES",
    "UNITS",
    "ActionRow",
    "BadParameter",
    "BarRow",
    "ClassificationRow",
    "MetricInfoRow",
    "MetricRow",
    "PillarRow",
    "PreviousRunRow",
    "RunChanged",
    "RunRow",
    "ScreenParams",
    "ScreenRow",
    "SectorRow",
    "SecurityParams",
    "SnapshotRow",
    "SymbolRow",
    "TilesRow",
    "awaiting",
    "closes",
    "delta",
    "exact",
    "one_decimal",
    "parse",
    "parse_all",
    "partial",
    "previous_run",
    "price",
    "read_screen",
    "resolve_run",
    "run_payload",
    "screen_params",
    "screen_payload",
    "screen_row",
    "sector",
    "security_params",
]
