"""The scored screen, read for the dashboard and for Steven (ui-swap spec D6).

Pure modules and reading modules are kept apart, as `screener.ingest` keeps
`parse` from `load`. `rows`, `params` and `shape` are pure: typed records parsed
from either a psycopg cursor or a `playground.Result`, query strings refused by
name, and JSON built from typed rows. `queries` holds every statement as a
literal. `read` resolves which night is served and reads it, and `explain`
re-runs scoring's explaining forms for one security under the run's own view,
giving each metric one of six statuses.
"""

from screener.screen.explain import (
    ABSENT,
    DEPENDS,
    FUNDAMENTALS,
    MISMATCH,
    OK,
    PRICE,
    REFRESHED,
    UNCHECKED,
    UNEXPECTED,
    Check,
    Reproduction,
    check,
    reproduce,
    reproduce_values,
    view_offset,
)
from screener.screen.params import (
    DEFAULT_LIMIT,
    MAX_LIMIT,
    MAX_OFFSET,
    MAX_SYMBOL,
    PARTIALS,
    SORTS,
    BadParameter,
    ScreenParams,
    SecurityParams,
    screen_params,
    security_params,
)
from screener.screen.read import (
    CHART_CLOSES,
    CLOSE_LOOKBACK_DAYS,
    SPARKLINE_CLOSES,
    AmbiguousSymbol,
    RunChanged,
    UnknownSymbol,
    previous_run,
    read_screen,
    read_security,
    resolve_run,
)
from screener.screen.shape import (
    ALL_CODES,
    MULTIPLE,
    PERCENT,
    PILLAR_KEYS,
    PILLAR_ORDER,
    UNITS,
    awaiting,
    closes,
    delta,
    exact,
    listed,
    one_decimal,
    partial,
    price,
    run_payload,
    screen_payload,
    screen_row,
    sector,
    security_payload,
    unscored_payload,
)
from screener.screen.rows import (
    ActionRow,
    BarRow,
    ClassificationRow,
    MetricInfoRow,
    MetricRow,
    PillarRow,
    PreviousRunRow,
    RunRow,
    ScreenRow,
    SectorRow,
    SnapshotRow,
    SymbolRow,
    TilesRow,
    parse,
    parse_all,
)

__all__ = [
    "ABSENT",
    "ALL_CODES",
    "CHART_CLOSES",
    "CLOSE_LOOKBACK_DAYS",
    "DEFAULT_LIMIT",
    "DEPENDS",
    "FUNDAMENTALS",
    "MAX_LIMIT",
    "MAX_OFFSET",
    "MAX_SYMBOL",
    "MISMATCH",
    "MULTIPLE",
    "OK",
    "PARTIALS",
    "PERCENT",
    "PILLAR_KEYS",
    "PILLAR_ORDER",
    "PRICE",
    "REFRESHED",
    "SORTS",
    "SPARKLINE_CLOSES",
    "UNCHECKED",
    "UNEXPECTED",
    "UNITS",
    "ActionRow",
    "AmbiguousSymbol",
    "BadParameter",
    "BarRow",
    "Check",
    "ClassificationRow",
    "MetricInfoRow",
    "MetricRow",
    "PillarRow",
    "PreviousRunRow",
    "Reproduction",
    "RunChanged",
    "RunRow",
    "ScreenParams",
    "ScreenRow",
    "SectorRow",
    "SecurityParams",
    "SnapshotRow",
    "SymbolRow",
    "TilesRow",
    "UnknownSymbol",
    "awaiting",
    "check",
    "closes",
    "delta",
    "exact",
    "listed",
    "one_decimal",
    "parse",
    "parse_all",
    "partial",
    "previous_run",
    "price",
    "read_screen",
    "read_security",
    "reproduce",
    "reproduce_values",
    "resolve_run",
    "run_payload",
    "screen_params",
    "screen_payload",
    "screen_row",
    "sector",
    "security_params",
    "security_payload",
    "unscored_payload",
    "view_offset",
]
